language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
jobs:
  allow_failures:
    - python: nightly
install:
  - pip install -r ./requirements-dev.txt
  - pip install coveralls
script:
  - ./test.py --with-coverage -v
after_success:
  cd tests && coveralls
